development:
  adapter: mysql
  database: six_months_development
  username: root
  password: 

production:
  adapter: mysql
  database: six_months_production
  username: root
  password: 0utKast

test:
  adapter: mysql
  database: six_months_test
  username: root
  password:

staging:
  adapter: mysql
  database: six_months_staging
  username: inuda
  password: inov