---
  environment: development
  chdir: /Users/kev/6-month-me
  address: 127.0.0.1
  port: 4567
  pid: /Users/kev/6-month-me/tmp/thin.pid
  rackup: /Users/kev/6-month-me/thin/config.ru
  log: /Users/kev/6-month-me/log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true