---
  environment: production
  chdir: /path/to/app/current/myapp
  address: 127.0.0.1
  user: root
  group: root
  port: 4567
  pid: /path/to/app/current/myapp/tmp/thin.pid
  rackup: /path/to/app/current/myapp/thin/config.ru
  log: /path/to/app/current/myapp/log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true